version: 2
jobs:
  build:
    docker:
      - image: cimg/base:stable

    steps:
      - run:
          name: Setup variables
          command: |
            echo 'export IMAGE_NAME=$DOCKER_USER/dind-ruby' >> $BASH_ENV

      - checkout
      - setup_remote_docker
      - run: ./go build
      - run: ./go test
      - run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
      - run: ./go publish
      - run: TAG=latest ./go publish

workflows:
  version: 2
  pipeline:
    jobs:
      - build:
          context: docker-context
